swagger: '2.0'
info:
  version: 0.0.1
  title: Search API
paths:
  /v2.0/search/local-land-charge:
    get:
      summary: "Get local land charges"
      description: "Get local land charges"
      parameters:
      - name: page
        in: query
        type: number
        required: false
        description: Page of results to be returned
      - name: pageSize
        in: query
        type: number
        required: false
        description: Number of results that should appear in a page
      responses:
        200:
          description: Search Successful
          schema:
            $ref: '#/definitions/results'
        404:
          description: No results found
          schema:
            type: object
            properties:
              error_message:
                type: string
                example: No land charges found
              error_code:
                type: number
                example: 404
        500:
          description: Server error
          schema:
            type: object
            properties:
              error_message:
                type: string
                example: Something went wrong
              error_code:
                type: number
                example: 500
    post:
      summary: Search for land charges by geographic information
      description: Search for land charges by geographic information
      parameters:
        -
          in: body
          name: Search
          schema:
            type: object
            properties:
              coordinates:
                type: array
                items:
                  type: array
                  description: Polygon GeoJSon geometry
                  items:
                    type: array
                    description: GeoJSon 2D Point
                    minItems: 2
                    maxItems: 2
                    items:
                      type: number
              type:
                type: string
                enum:
                - 'Polygon'
                - 'MultiPolygon'
              crs:
                type: object
                properties:
                  type:
                    type: string
                  properties:
                    type: object
                    properties:
                      name:
                        type: string
      responses:
        200:
          description: Search Successful
          schema:
            $ref: '#/definitions/results'
        400:
          description: Bad request
          schema:
            type: object
            properties:
              error_message:
                type: string
                example: Failed to provide a search area
              error_code:
                type: number
                example: 400
        404:
          description: No results found
          schema:
            type: object
            properties:
              error_message:
                type: string
                example: No land charges found
              error_code:
                type: number
                example: 404
        500:
          description: Server error
          schema:
            type: object
            properties:
              error_message:
                type: string
                example: Something went wrong
              error_code:
                type: number
                example: 500
        507:
          description: Too many results
          schema:
            type: object
            properties:
              error_message:
                type: string
                example: Too many charges, search a smaller area
              error_code:
                type: number
                example: 507

  /search/local-land-charge:
    get:
      summary: "Get local land charges"
      description: "Get local land charges"
      parameters:
      - name: boundingBox
        in: query
        type: string
        required: false
        description: Base64 encoded extent that results should appear in
      responses:
        200:
          description: Search Successful
          schema:
            type: array
            items:
              $ref: '#/definitions/land_charge'
        404:
          description: No results found
          schema:
            type: object
            properties:
              error_message:
                type: string
                example: No land charges found
              error_code:
                type: number
                example: 404
        422:
          description: Unable to decode bounding box
          schema:
            type: object
            properties:
              error_message:
                type: string
                example: Unprocessable Entity. Incorrect padding
              error_code:
                type: number
                example: 422
        500:
          description: Server error
          schema:
            type: object
            properties:
              error_message:
                type: string
                example: Something went wrong
              error_code:
                type: number
                example: 500
  /search/local-land-charge/{charge_id}:
    get:
      summary: Get local land charge
      description: Get local land charge
      parameters:
      - name: charge_id
        in: path
        type: string
        required: true
        description: Charge ID e.g. LLC-52
      responses:
        200:
          description: Search successful
          schema:
            type: array
            items:
              $ref: '#/definitions/land_charge'
        404:
          description: No results found
          schema:
            type: object
            properties:
              error_message:
                type: string
                example: No land charges found
              error_code:
                type: number
                example: 404
        500:
          description: Server error
          schema:
            type: object
            properties:
              error_message:
                type: string
                example: Something went wrong
              error_code:
                type: number
                example: 500

  /search/local-land-charge/{charge_id}/history:
    get:
      summary: Get local land charge history
      description: Get local land charge history
      parameters:
      - name: charge_id
        in: path
        type: string
        required: true
        description: Charge ID e.g. LLC-52
      responses:
        200:
          description: Search successful
          schema:
            type: array
            items:
              $ref: '#/definitions/charge-history'
        404:
          description: No results found
          schema:
            type: object
            properties:
              error_message:
                type: string
                example: No land charges found
              error_code:
                type: number
                example: 404
        500:
          description: Server error
          schema:
            type: object
            properties:
              error_message:
                type: string
                example: Something went wrong
              error_code:
                type: number
                example: 500


security:
  - JWTAuth: []

securityDefinitions:
  JWTAuth:
    type: apiKey
    in: header
    name: Authorizaton

definitions:
  land_charge:
    type: object
    properties:
      type:
        type: string
      item:
        type: object
        properties:
          charge-type:
            type: string
          further-information-location:
            type: string
          author:
            $ref: '#/definitions/author'
          originating-authority:
            type: string
          registration-date:
            type: string
          instrument:
            type: string
          statutory-provision:
            type: string
          charge-geographic-description:
            type: string
          local-land-charge:
            type: number
          geometry:
            type: object
            properties:
              type:
                type: string
              features:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    geometry:
                      type: object
                      properties:
                        type:
                          type: string
                        coordinates:
                          type: array
                          items:
                            type: object
                    properties:
                      type: object
                      properties:
                        id:
                          type: number
          start-date:
            type: string
      id:
        type: number
      cancelled:
        type: boolean
      display_id:
        type: string
      geometry:
        type: object
        properties:
          type:
            type: string
          features:
            type: array
            items:
              type: object
              properties:
                type:
                  type: string
                geometry:
                  type: object
                  properties:
                    type:
                      type: string
                    coordinates:
                      type: object
                properties:
                  type: object
                  properties:
                    id:
                      type: number
  results:
    type: object
    properties:
      current_page:
        type: number
        description: The current page the results represent
        example: 2
      page_size:
        type: number
        description: The number of results per page
        example: 10
      total_results:
        type: number
        description: Total number of results
        example: 1000
      paged:
        type: boolean
        description: Indicator that the results are paged
        example: True
      results:
        type: array
        items:
          $ref: '#/definitions/land_charge'
    required:
      - paged
      - results
  charge-history:
    type: object
    properties:
      entry-number:
        type: number
        example: 12345
      cancelled:
        type: boolean
        example: false
      entry-timestamp:
        type: string
        example: "2017-07-17T13:16:59.886789"
      author:
        $ref: '#/definitions/author'
  author:
    type: object
    properties:
      organisation:
        type: string
        example: "HM Land Registry"
      full-name:
        type: string
        example: "Joe Bloggs"
      email:
        type: string
        example: "joe@bloggs.com"